[package]
name = "avalanche-installer"
version = "0.0.15" # https://crates.io/crates/avalanche-installer
edition = "2021"
rust-version = "1.66"
publish = true
description = "Avalanche installer"
repository = "https://github.com/gyuho/avalanche-installer"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
compress-manager = "0.0.4"
http-manager = "0.0.7"
log = "0.4.17"
random-manager = "0.0.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91" # https://github.com/serde-rs/json
tokio = "1.24.1" # https://github.com/tokio-rs/tokio/releases

[dev-dependencies]
env_logger = "0.10.0"
tokio-test = "0.4.2"
