[package]
name = "avalanche-installer"
version = "0.0.9" # https://crates.io/crates/avalanche-installer
edition = "2021"
rust-version = "1.65"
publish = true
description = "Avalanche installer"
repository = "https://github.com/gyuho/avalanche-installer"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
compress-manager = "0.0.2"
http-manager = "0.0.5"
log = "0.4.17"
random-manager = "0.0.1"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89" # https://github.com/serde-rs/json

[dev-dependencies]
env_logger = "0.10.0"
tokio-test = "0.4.2"
