[package]
name = "avalanche-installer"
version = "0.0.3" # https://crates.io/crates/avalanche-installer
edition = "2021"
rust-version = "1.62"
publish = true
description = "Avalanche installer"
repository = "https://github.com/gyuho/avalanche-installer"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
compress-manager = "0.0.2"
http-manager = "0.0.1"
log = "0.4.17"
random-manager = "0.0.1"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"

[dev-dependencies]
env_logger = "0.9.0"
tokio-test = "0.4.2"
